import {debtTotals} from './debt-ledger.mjs';
import {readProvider} from './receipts.mjs';
import {mountWallet} from './wallet.mjs';
import './style.css';import './lending.css';import './koriko-theme.css';
import {BrowserProvider,Contract,formatUnits,parseUnits} from 'ethers';
import {mockValuation,accruedInterest} from './valuation.mjs';
import {deployLending,pledgeValuation,fundPool,borrow,repay,liquidate,lendingContract,ERC20_ABI} from './lending-client.mjs';
const $=s=>document.querySelector(s),usd=x=>(Number(x)/1e6).toFixed(6),date=t=>new Date(t*1000).toLocaleString('zh-TW');let mode='demo',provider,signer,state,quote,sim,busy=false;
let demoLoans=[];let renderRevision=0;
try{demoLoans=JSON.parse(localStorage.getItem('korikoex-demo-loans-v1')||'[]').map(l=>({...l,principal:BigInt(l.principal),...(l.closedInterest!==undefined?{closedInterest:BigInt(l.closedInterest)}:{})}));sim=demoLoans.at(-1);}catch{demoLoans=[];}
function saveDemo(){localStorage.setItem('korikoex-demo-loans-v1',JSON.stringify(demoLoans,(_,v)=>typeof v==='bigint'?String(v):v));}
const escapeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=Math.floor(Date.now()/1000),start=new Date((now-10*86400)*1000).toISOString().slice(0,10),expiry=new Date((now+20*86400)*1000).toISOString().slice(0,10);
$('#app').innerHTML=`<header><a class="brand" href="./"><img class="brand-logo" src="./koriko-logo.svg" alt="KorikoEX 蝴蝶結與掃帚標誌"><b>KorikoEX</b><span>克里克交易所</span></a><div class="headright"><a class="old-market" href="./exchange.html">ERC-3643 市場</a><select id="wallet-select" aria-label="選擇錢包" hidden></select><span id="wallet-status" class="wallet-status" role="status">偵測錢包中</span><button id="connect">綁定錢包</button><button id="disconnect" hidden>斷開錢包</button></div></header><main><section class="koriko-hero" aria-label="克里克城市主視覺"><img src="./koriko-city.jpg" alt="魔女宅急便中的克里克城市街景，琪琪與蜻蜓飛越繁忙廣場"><div class="koriko-title"><span>KORIKOEX / INTELLIGENT EXCHANGE</span><h1>克里克交易所</h1><p class="brand-slogan">每座想飛的城市都需要港口；在克里克交易所，用信任交換你的下一次展翅</p><p class="brand-story">&lt;&lt;魔女宅急便&gt;&gt;裡琪琪落腳的海邊城市叫克里克：我們就是你在資金路上最安心的補給站。</p></div><a class="koriko-credit" href="https://www.ghibli.jp/works/majo/" target="_blank" rel="noopener">《魔女宅急便》官方劇照 © 1989 Studio Ghibli 等 ↗</a></section><div class="eyebrow">DUAL AGENT / SUBSCRIPTION COLLATERAL</div><div class="top"><div><h2 class="workspace-title">用訂閱殘值，開啟一筆借款</h2><p>OpenAI 與 Claude 分別估價，保守核貸，利息與抵押狀態隨時可查。</p></div><span class="demo">Testnet PoC</span></div><div class="mode-switch"><button id="demo-mode" class="active">互動展示</button><button id="chain-mode">Sepolia 合約</button><span id="mode-label">瀏覽器模擬，不送出鏈上交易</span></div><div class="notice"><b>模擬抵押憑證</b><span>訂閱帳號尚無可執行的轉讓／沒收權利，真正可清算的帳號抵押價值為 0。本 PoC 不收帳密、API Key、Cookie 或登入憑證。</span></div>
<div class="stats"><div><label>雙 Agent 估價</label><strong>未接 API <small>模擬估價</small></strong></div><div><label>貸款成數</label><strong>30% <small>較低估價</small></strong></div><div><label>年利率</label><strong>12% <small>單利</small></strong></div><div><label>清算觸發</label><strong>到期未還 <small>移交憑證</small></strong></div></div>
<div class="workspace"><section class="market"><div class="sectionhead"><h2>02 訂閱資料</h2><span>自行填寫 · 尚未驗證供應商</span></div><div class="fields"><label>服務<select id="service"><option value="codex">ChatGPT / Codex</option><option value="claude">Claude</option></select></label><label>訂閱等級<input id="plan" value="Pro（示範）" maxlength="50"></label><label>本期實付 USD<input id="paid" type="number" value="200" min="0.01" max="10000" step="0.01"></label><label>本期開始（UTC）<input id="start" type="date" value="${start}"></label><label>訂閱到期（UTC）<input id="expiry" type="date" value="${expiry}"></label></div><button id="bind-account" class="value-button">模擬綁定 ChatGPT／Claude 帳號並估價</button><p id="account-binding" class="expiry" role="status">尚未模擬綁定帳號</p><button id="value" class="textbutton">依目前資料重新估價</button><div class="sectionhead agent-head"><h2>03 殘值估價</h2><span id="quote-status">尚未估價</span></div><div class="agent-results"><div><label><img class="agent-logo" src="./codex-logo.png" alt="OpenAI"> OPENAI AGENT <small>模擬</small></label><strong id="oa-value">—</strong><p id="oa-reason">等待訂閱資料</p></div><div><label><img class="agent-logo" src="./claude-logo.svg" alt="Claude"> CLAUDE AGENT <small>模擬</small></label><strong id="cl-value">—</strong><p id="cl-reason">等待訂閱資料</p></div></div><div class="valuation-total"><span>保守殘值</span><b id="residual">—</b><span>最多可借</span><b id="max-loan">—</b></div><p class="expiry">殘值上限＝本期實付 × 剩餘時間／本期長度。模擬 agents 分別折價 35% 與 40%，採較低結果。實付數字為示範輸入，不是官方訂閱報價。</p></section>
<aside><div class="sectionhead"><h2>05 確認借款</h2><span id="currency">展示 USD 單位</span></div><label for="principal">借款本金</label><input class="loan-input" id="principal" type="number" value="1" min="0.01" max="1000" step="0.01"><label for="term">借款期限</label><select id="term"><option value="604800">7 天</option><option value="86400">1 天</option><option value="60">1 分鐘（到期演示）</option></select><div class="calculation"><div><span>每天利息（單利）</span><b id="daily">0.003288</b></div><div><span>期限內預估利息</span><b id="projected">0.023014</b></div><div><span>到期預估總還款</span><b id="projected-debt">10.023014</b></div><div><span>借款到期</span><b id="due">—</b></div></div><button id="borrow" class="primary" disabled>請先估價</button><p class="micro">本金＋累計利息全額還清才釋放憑證。每天利息＝本金×12%÷365，實際按秒累計並向上取至 0.000001。</p><div id="message" role="status"></div></aside></div>
<section class="loan-section"><div class="sectionhead"><h2>我的欠款與借款紀錄</h2><div id="time-controls"><button id="advance-day">展示時間 +1 天</button><button id="advance-due">展示時間至到期</button></div></div><div id="debt-summary" class="debt-summary" role="status"></div><p id="debt-scope" class="micro"></p><button id="refresh-loans" class="textbutton">重新讀取我的欠款</button><div id="loan-card" class="loan-empty">尚無借款。先估價，再抵押模擬訂閱憑證。</div></section>
<section class="deployment" id="deployment"><div><div class="eyebrow">SEPOLIA WORKSHOP</div><h2>01 連接錢包與準備借貸池</h2><p>部署雙 Oracle 與抵押／借貸合約，登錄估價後再借款。所有交易由瀏覽器錢包簽署。<br>清算只移交 SUB-MOCK 憑證，不能接管 Codex／Claude 帳號。</p></div><div class="deploy-actions"><select id="payment"><option value="circle">Circle Sepolia USDC</option></select><button id="deploy" disabled>先連接錢包</button><button id="fund" disabled>注入 5 測試 USDC</button><button id="attest" disabled>登錄抵押與雙估價</button></div><pre id="log" role="status">尚未連接錢包。公開測試網成果需實際交易 hash，不以本地測試替代。</pre></section>
<section class="loan-section"><h2>Sepolia 交易收據</h2><div id="chain-receipts" class="chain-receipts">尚無已確認的 Sepolia 交易。</div></section><section class="evidence"><h2>估價、權利與清算</h2><div><p>兩位 agent 分開估價，採較低結果，分歧過大則拒絕核貸。API 尚未設定，現在使用明確標示的確定性模擬。</p><p>借款期限須早於訂閱到期。清算需要 keeper 或使用者送出交易，不會自行執行；清算後記錄未回收債務，沒收憑證不代表貸方已回收本金。</p><p id="test-summary">正在讀取本地合約測試證據…</p></div></section><footer><span>克里克交易所 · RWA 工作坊 · 2026.10.01</span><nav><a href="https://faucet.circle.com/" target="_blank" rel="noopener">測試 USDC Faucet</a><a href="https://github.com/k66inthesky/KorikoEX" target="_blank" rel="noopener">GitHub ↗</a><button id="download" class="textbutton">下載合約證據</button></nav></footer></main><dialog id="account-dialog" aria-labelledby="account-dialog-title"><h2 id="account-dialog-title">模擬綁定訂閱帳號</h2><p>選擇示範帳號資料即可估價，不需要登入或提供帳密。</p><form id="account-form"><label>帳號服務<select id="account-provider"><option value="codex">ChatGPT / Codex</option><option value="claude">Claude</option></select></label><label>訂閱等級<select id="account-tier"></select></label><label>本期實付 USD<input id="account-paid" type="number" min="0.01" max="10000" step="0.01" required></label><label>本期開始（UTC）<input id="account-start" type="date" required value="${start}"></label><label>到期日期（UTC）<input id="account-expiry" type="date" required value="${expiry}"></label><p id="account-tier-note">金額是模擬預設，請改成本期實付金額。</p><div class="account-dialog-actions"><button type="button" id="account-cancel">取消</button><button type="submit" class="primary">模擬綁定並計算殘值</button></div><p id="account-error" role="alert"></p></form></dialog>`;
// Keep setup above valuation and registration above loan confirmation in DOM order.
const setupSection=$('#deployment'),workspace=$('.workspace');workspace.before(setupSection);
const registration=document.createElement('section');registration.className='registration-step';
registration.innerHTML='<h2>04 登錄抵押與雙估價</h2><p class="micro">互動展示會在借款時模擬鎖定憑證；Sepolia 模式須先完成登錄，再向下確認借款。</p>';
registration.append($('#attest'));$('.market').append(registration);
$('#deploy').before(Object.assign(document.createElement('p'),{id:'setup-note',className:'micro',textContent:'互動展示無須部署；Sepolia 首次使用：綁定錢包 → 部署借貸池 → 注入流動性。已建立的池可直接使用。'}));
function renderDebtSummary(rows){const totals=debtTotals(rows);$('#debt-summary').textContent=`目前欠款 ${usd(totals.outstanding)} ${mode==='demo'?'展示 USD':'Sepolia USDC'} · ${totals.count} 筆未結清`;if(totals.unrecovered>0n)$('#debt-summary').textContent+=`（含已清算未回收 ${usd(totals.unrecovered)}）`;$('#debt-scope').textContent=mode==='demo'?'以下是本次瀏覽器模擬的逐筆紀錄，不是真實帳號或鏈上債務。':'顯示目前綁定錢包在這個借貸池的逐筆紀錄；已還清為 0，已清算未回收金額另外標示。';}
function syncBorrowButton(){const registered=state?.collateralQuote&&quote&&JSON.stringify(state.collateralQuote.subscription)===JSON.stringify(quote.subscription);$('#borrow').disabled=busy||!quote||quote.reviewRequired||(mode==='chain'&&(!signer||!state?.deployed||!registered));}
function log(s){$('#log').textContent+='\n'+s;}
function renderTransactions(){const area=$('#chain-receipts');if(!area)return;area.replaceChildren();for(const tx of state?.transactions||[]){if(!/^0x[a-fA-F0-9]{64}$/.test(tx.hash))continue;const a=document.createElement('a');a.href='https://sepolia.etherscan.io/tx/'+tx.hash;a.target='_blank';a.rel='noopener';a.textContent=tx.label+' · '+tx.hash.slice(0,12)+'… ↗';area.append(a);}if(!area.childNodes.length)area.textContent='尚無已確認的 Sepolia 交易。';}
function save(s){state=s;renderTransactions();localStorage.setItem('korikoex-lending-usdc-v2:'+s.owner.toLowerCase(),JSON.stringify(s));}
function input(){const paid=Number($('#paid').value),startsAt=Date.parse($('#start').value+'T00:00:00Z')/1000,expiresAt=Date.parse($('#expiry').value+'T00:00:00Z')/1000;return {provider:$('#service').value,plan:$('#plan').value,paidMicros:Math.round(paid*1e6),startsAt,expiresAt};}
function estimates(){const n=Number($('#principal').value),term=Number($('#term').value);if(!Number.isFinite(n)||n<=0||n>10000)return;const micros=Math.round(n*1e6);$('#daily').textContent=usd(accruedInterest(micros,86400));$('#projected').textContent=usd(accruedInterest(micros,term));$('#projected-debt').textContent=usd(BigInt(micros)+accruedInterest(micros,term));$('#due').textContent=date((mode==='demo'&&sim?sim.now:Math.floor(Date.now()/1000))+term);}
function showQuote(q){quote=q;$('#oa-value').textContent=usd(q.agents[0].valueMicros)+' USD';$('#cl-value').textContent=usd(q.agents[1].valueMicros)+' USD';$('#oa-reason').textContent=q.agents[0].reason;$('#cl-reason').textContent=q.agents[1].reason;$('#residual').textContent=usd(q.residualMicros)+' USD';$('#max-loan').textContent=usd(q.demoMaxBorrowMicros)+' USD';$('#quote-status').textContent='模擬估價 · 15分鐘有效';$('#borrow').disabled=busy||q.reviewRequired;$('#borrow').textContent=mode==='demo'?'抵押並演示借款':'抵押並借入測試 USDC';$('#attest').disabled=busy||!state?.deployed||q.reviewRequired;syncBorrowButton();}
function switchMode(m){mode=m;$('#demo-mode').classList.toggle('active',m==='demo');$('#chain-mode').classList.toggle('active',m==='chain');$('#mode-label').textContent=m==='demo'?'瀏覽器模擬，不送出鏈上交易':'Sepolia 真實交易，需要錢包確認';$('#time-controls').hidden=m!=='demo';$('#deployment').classList.toggle('chain-active',m==='chain');$('#setup-note').textContent=m==='demo'?'互動展示無须錢包或部署，可繼續往下模擬綁定訂閱。':'首次使用：綁定錢包 → 部署借貸池 → 注入流動性；已建立的池可直接使用。';$('#currency').textContent=m==='demo'?'展示 USD 單位':'Circle 測試 USDC';if(quote)showQuote(quote);estimates();renderLoans();}
function pendingMsg(e){if(e.code===-32002){$('#message').textContent='錢包已有待確認請求，請開啟 MetaMask 完成確認，再按連接。';return;}$('#message').textContent=e.shortMessage||e.reason||e.message||String(e);}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){pendingMsg(e);log('停止：'+(e.shortMessage||e.message));}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);$('#deploy').disabled=!signer||Boolean(state?.deployed);$('#fund').disabled=!state?.deployed;$('#attest').disabled=!state?.deployed||!quote;$('#borrow').disabled=!quote||quote.reviewRequired;await renderLoans();}}
$('#demo-mode').onclick=()=>switchMode('demo');$('#chain-mode').onclick=()=>switchMode('chain');
for(const id of ['service','plan','paid','start','expiry'])$('#'+id).oninput=()=>{quote=null;$('#quote-status').textContent='資料已變更，請重新估價';$('#borrow').disabled=true;$('#attest').disabled=true;};$('#principal').oninput=estimates;$('#term').onchange=estimates;
$('#value').onclick=()=>{try{showQuote(mockValuation(input()));$('#message').textContent='這是模擬估價，沒有呼叫 OpenAI／Claude API。';}catch(e){pendingMsg(e)}};
mountWallet({isBusy:()=>busy,onError:pendingMsg,onConnect:async connection=>{({provider,signer}=connection);provider=await readProvider(provider);const owner=await signer.getAddress();state=JSON.parse(localStorage.getItem('korikoex-lending-usdc-v2:'+owner.toLowerCase())||'null');$('#deploy').disabled=Boolean(state?.deployed);$('#deploy').textContent=state?.deployed?'借貸池已建立':'部署 Sepolia USDC 借貸池';$('#fund').disabled=!state?.deployed;$('#attest').disabled=!state?.deployed||!quote;switchMode('chain');renderTransactions();log('已連接 Sepolia · Circle USDC');log('測試 ETH 餘額：'+formatUnits(await provider.getBalance(owner),18));},onDisconnect:async()=>{provider=signer=state=undefined;$('#deploy').disabled=true;$('#fund').disabled=true;$('#attest').disabled=true;$('#borrow').disabled=true;renderTransactions();switchMode('demo');}});
$('#deploy').onclick=()=>action(async()=>{if(!signer)throw Error('先連接錢包');state=await deployLending(signer,state||{},log,save,false);$('#deploy').textContent='借貸池已建立';$('#payment').disabled=true;$('#message').textContent='已使用 Circle 官方 Sepolia USDC，請注入測試流動性。';switchMode('chain');});
$('#fund').onclick=()=>action(async()=>{const r=await fundPool(signer,state,5_000000n);state.transactions.push({label:'注入5測試USDC',hash:r.hash,block:r.blockNumber});save(state);log('借貸池入金成功：'+r.hash);});
$('#attest').onclick=()=>action(async()=>{if(!quote)throw Error('先估價');const id=await pledgeValuation(signer,state,quote,log,save);$('#message').textContent='已登錄模擬抵押憑證 #'+id+' 與兩筆估價。Oracle 由 PoC 錢包操作，不代表獨立授權。';});
$('#borrow').onclick=()=>action(async()=>{if(!quote)throw Error('先估價');const n=Number($('#principal').value);if(!Number.isFinite(n)||n<=0||n>10000)throw Error('請輸入正數借款額');const amount=BigInt(Math.round(n*1e6)),term=Number($('#term').value),nnow=Math.floor(Date.now()/1000);if(nnow>=quote.validUntil)throw Error('估價已過期，請重新估價');if(amount>BigInt(quote.demoMaxBorrowMicros))throw Error('本金超過估價的30%上限');if(nnow+term>=quote.subscription.expiresAt)throw Error('借款須早於訂閱到期');
 if(mode==='demo'){sim={id:demoLoans.length+1,subscription:{...quote.subscription},principal:amount,startedAt:nnow,dueAt:nnow+term,now:nnow,status:'active'};demoLoans.push(sim);saveDemo();$('#message').textContent='瀏覽器展示：已鎖定模擬憑證並記錄借款，未送出鏈上交易。';}
 else{if(!state?.collateralQuote||JSON.stringify(state.collateralQuote.subscription)!==JSON.stringify(quote.subscription))throw Error('請先登錄此筆估價與抵押');const r=await borrow(signer,state,amount,term);state.loanIds??=[];if(!state.loanIds.includes(state.collateralId))state.loanIds.push(state.collateralId);state.transactions.push({label:'抵押借款',hash:r.hash,block:r.blockNumber});save(state);log('借款已核對抵押鎖定與狀態：'+r.hash);$('#message').textContent='Sepolia 借款成功，請保留本金與足夠利息以還款。';}});
function demoLoan(loan){const sim=loan;const idiv=document.createElement('div');if(!sim){idiv.className='loan-empty';idiv.textContent='尚無借款。先估價，再抵押模擬訂閱憑證。';return idiv;}const elapsed=Math.min(sim.now,sim.dueAt)-sim.startedAt,i=sim.closedInterest??accruedInterest(Number(sim.principal),elapsed),overdue=sim.now>=sim.dueAt;const stateText=sim.status==='repaid'?'已還清 · 憑證已釋放':sim.status==='liquidated'?'已清算 · 模擬憑證已移交貸方':overdue?'已到期 · 等待清算':'借款中 · 抵押憑證已鎖定';idiv.innerHTML=`<div class="loan-status">#${sim.id} · ${sim.subscription.provider==='codex'?'ChatGPT / Codex':'Claude'} ${escapeText(sim.subscription.plan)} · ${stateText}</div><div class="loan-numbers"><div><label>本金</label><b>${usd(sim.principal)}</b></div><div><label>累計利息</label><b>${usd(i)}</b></div><div><label>目前欠款</label><b>${usd(sim.status==='repaid'?0n:sim.principal+i)}</b></div><div><label>到期日</label><b>${date(sim.dueAt)}</b></div></div>`;if(sim.status==='active'){const btn=document.createElement('button');btn.textContent=overdue?'演示到期沒收憑證':'演示還本付息';btn.onclick=()=>{sim.closedInterest=i;sim.status=overdue?'liquidated':'repaid';saveDemo();renderLoans();};idiv.append(btn);}return idiv;}
async function renderLoans(){const area=$('#loan-card');const revision=++renderRevision;if(mode==='demo'){const rows=demoLoans.map(l=>({principal:l.principal,interest:l.closedInterest??accruedInterest(Number(l.principal),Math.min(l.now,l.dueAt)-l.startedAt),status:({active:1,repaid:2,liquidated:3})[l.status]}));renderDebtSummary(rows);area.replaceChildren(...(demoLoans.length?demoLoans.map(demoLoan):[demoLoan(null)]));syncBorrowButton();return;}if(!state?.deployed||!provider){$('#debt-summary').textContent='尚未讀取鏈上欠款';$('#debt-scope').textContent='請先連接錢包與建立借貸池。';area.textContent='連接錢包並部署後，讀取鏈上借款狀態。';syncBorrowButton();return;}const pool=lendingContract('SubscriptionLending',state.addresses.pool,provider);const cash=new Contract(state.addresses.cash,ERC20_ABI,provider);let balance=await cash.balanceOf(state.addresses.pool);$('#currency').textContent='Sepolia USDC'+' · 池餘額 '+formatUnits(balance,6);const ids=[...(state.loanIds||[])];const deployment=state.transactions.find(t=>t.label==='部署 pool');if(deployment?.block){const end=await provider.getBlockNumber();for(let start=Number(deployment.block);start<=end;start+=2000){const events=await pool.queryFilter(pool.filters.Borrowed(null,state.owner),start,Math.min(start+1999,end));for(const event of events){const id=String(event.args.id);if(!ids.includes(id))ids.push(id);}}state.loanIds=ids;save(state);}if(state.collateralId&&!ids.includes(state.collateralId)){const recovered=await pool.loans(state.collateralId);if(recovered.status!==0n){ids.push(state.collateralId);state.loanIds=ids;save(state);}}if(revision!==renderRevision)return;const rows=[];area.replaceChildren();if(!ids.length){renderDebtSummary([]);area.textContent='尚無鏈上借款。先登錄抵押與估價。';syncBorrowButton();return;}const n=(await provider.getBlock('latest')).timestamp;
 for(const id of ids){const l=await pool.loans(id);if(l.borrower.toLowerCase()!==state.owner.toLowerCase()||l.status===0n)continue;const i=await pool.interest(id),due=l.status===2n?0n:l.principal+i;rows.push({principal:l.principal,interest:i,status:Number(l.status)});const el=document.createElement('article');el.className='onchain-loan';const title=document.createElement('b');title.textContent='#'+id+' · '+(['無借款','抵押中','已還清','已清算 · 未回收'][Number(l.status)])+' · 到期 '+date(Number(l.dueAt));const details=document.createElement('p');details.textContent='本金 '+usd(l.principal)+'，累計利息 '+usd(i)+'，目前欠款 '+usd(due)+' Sepolia USDC';el.append(title,details);if(l.status===1n){const button=document.createElement('button');button.disabled=busy;button.textContent=n>=l.dueAt?'逾期清算／移交憑證':'全額還本付息';button.onclick=()=>action(async()=>{const r=n>=l.dueAt?await liquidate(signer,state,id):await repay(signer,state,id);state.transactions.push({label:n>=l.dueAt?'逾期清算':'還本付息',hash:r.hash,block:r.blockNumber});save(state);log('交易完成：'+r.hash);});el.append(button);}if(revision!==renderRevision)return;area.append(el);}
 renderDebtSummary(rows);syncBorrowButton();
}
$('#advance-day').onclick=()=>{for(const loan of demoLoans)if(loan.status==='active')loan.now+=86400;saveDemo();renderLoans()};$('#advance-due').onclick=()=>{for(const loan of demoLoans)if(loan.status==='active')loan.now=loan.dueAt;saveDemo();renderLoans()};
$('#download').onclick=()=>{const blob=new Blob([JSON.stringify(state||{status:'not-deployed',chainId:11155111,mode:'demo'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lending-sepolia-evidence.json';a.click();URL.revokeObjectURL(url);};

fetch('./lending-evidence.json').then(r=>r.ok?r.json():Promise.reject()).then(e=>$('#test-summary').textContent=`本地 EVM：${e.checks.length} 項借貸與風險檢查通過。已實測還本付息、逾期清算與資產移交。鏈 ID ${e.chainId}，不是公開 Sepolia 成果。`).catch(()=>$('#test-summary').textContent='本地測試收據未載入，請查看 GitHub。');
$('#refresh-loans').onclick=()=>renderLoans().catch(pendingMsg);
estimates();renderLoans();setInterval(()=>{if(mode==='chain'&&state?.deployed&&!busy)renderLoans().catch(pendingMsg)},15000);

// Demo tiers are scenario inputs, not provider pricing or verified account data.
const demoTiers={codex:[['Go',8],['Plus',20],['Pro',200]],claude:[['Pro',20],['Pro 5x',100],['Pro 20x',200],['Pro 25x（自訂模擬）',250]]};
function updateAccountTiers(){const tiers=demoTiers[$('#account-provider').value];$('#account-tier').replaceChildren(...tiers.map(([name,paid])=>{const option=document.createElement('option');option.value=name;option.textContent=name;option.dataset.paid=paid;return option}));updateAccountPaid();}
function updateAccountPaid(){$('#account-paid').value=$('#account-tier').selectedOptions[0].dataset.paid;$('#account-tier-note').textContent='金額是模擬預設，請改成本期實付金額。25x 為自訂情境，未宣稱是官方方案。';}
$('#bind-account').onclick=()=>{$('#account-provider').value=$('#service').value;updateAccountTiers();$('#account-error').textContent='';$('#account-dialog').showModal();};
$('#account-provider').onchange=updateAccountTiers;$('#account-tier').onchange=updateAccountPaid;
$('#account-cancel').onclick=()=>$('#account-dialog').close();
$('#account-form').onsubmit=e=>{e.preventDefault();try{const account={provider:$('#account-provider').value,plan:$('#account-tier').value,paidMicros:Math.round(Number($('#account-paid').value)*1e6),startsAt:Date.parse($('#account-start').value+'T00:00:00Z')/1000,expiresAt:Date.parse($('#account-expiry').value+'T00:00:00Z')/1000};const result=mockValuation(account);$('#service').value=account.provider;$('#plan').value=account.plan;$('#paid').value=account.paidMicros/1e6;$('#start').value=$('#account-start').value;$('#expiry').value=$('#account-expiry').value;showQuote(result);$('#account-binding').textContent='已模擬綁定 '+(account.provider==='codex'?'ChatGPT':'Claude')+' '+account.plan+'，到期 '+$('#expiry').value+'。資料未經供應商驗證。';$('#message').textContent='模擬綁定完成。雙 Agent 以剩餘實付價值為上限，採較低估價。';$('#account-dialog').close();}catch(error){$('#account-error').textContent=error.message;}};
