import {connectSepolia,discoverWallets,watchWallet} from './wallet.mjs';
import './style.css';
import {BrowserProvider,formatUnits} from 'ethers';
import {setup,trade,contract} from './protocol.mjs';
const app=document.querySelector('#app');
app.innerHTML=`<header><a class="brand" href="#"><img class="brand-logo" src="./koriko-logo.svg" alt="KorikoEX 蝴蝶結與掃帚標誌"><b>KorikoEX</b><span>克里克交易所</span></a><div class="headright"><span class="network">Sepolia · 測試網</span><select id="wallet-select" aria-label="選擇錢包" hidden></select><button id="connect">連接錢包</button></div></header>
<main><div class="eyebrow">ERC-3643 / ATOMIC DVP</div><div class="top"><div><h1>讓剩餘額度找到下一個需求者</h1><p>交易模型服務憑證，每筆交割都能核對付款與持有量。</p></div><span class="demo">模擬資產 PoC</span></div>
<div class="notice"><b>資產來源尚未授權</b><span>Codex／Claude 為第一波概念標的。這裡的憑證不兌換官方服務，不轉售個人帳戶或既有 credits。</span></div>
<div class="stats"><div><label>交易資格</label><strong id="identity">待連接錢包</strong></div><div><label>付款方式</label><strong>mUSD <small>測試代幣</small></strong></div><div><label>交割方式</label><strong>DvP <small>同筆交割</small></strong></div><div><label>憑證單位</label><strong>1,000 <small>模擬輸入 token</small></strong></div></div>
<div class="workspace"><section class="market"><div class="sectionhead"><h2>額度市場</h2><span id="inventory-note">示範報價，部署後讀取鏈上庫存</span></div><div class="offer active" tabindex="0" data-batch="codex" role="button" aria-label="選擇Codex憑證"><div class="logo">CX</div><div class="offername"><h3>Codex</h3><p>服務憑證 · CX-MOCK</p></div><div class="offerprice"><b>0.50</b><span>mUSD / 枚</span></div><div class="stock"><b id="codex-stock">—</b><span>鏈上庫存</span></div></div><div class="offer" tabindex="0" data-batch="claude" role="button" aria-label="選擇Claude憑證"><div class="logo claude">CL</div><div class="offername"><h3>Claude</h3><p>服務憑證 · CL-MOCK</p></div><div class="offerprice"><b>0.70</b><span>mUSD / 枚</span></div><div class="stock"><b id="claude-stock">—</b><span>鏈上庫存</span></div></div><p class="expiry">每批有效期 30 天。模型、輸入及輸出額度須分批定價。<br>本作品採固定價格庫存出售，尚未實作自由掛單市場。</p>
<div class="sectionhead receipts-head"><h2>交割收據</h2><button id="download" class="textbutton">下載證據 JSON</button></div><div id="receipts" class="empty">尚無公開測試網交割。完成交易後顯示實際 hash 與餘額變化。</div></section>
<aside><div class="sectionhead"><h2>買入憑證</h2><span id="selected">Codex</span></div><label for="units">數量（枚）</label><div class="quantity"><button id="minus" aria-label="減少數量">−</button><input id="units" type="number" min="1" max="1000" value="10" step="1"><button id="plus" aria-label="增加數量">＋</button></div><div class="calculation"><div><span>模擬輸入額度</span><b id="tokens">10,000 tokens</b></div><div><span>成交金額</span><b id="total">5.00 mUSD</b></div><div><span>PoC 交易費</span><b>0.00 mUSD</b></div><div><span>我的付款餘額</span><b id="balance">—</b></div><div><span>我的憑證</span><b id="holdings">—</b></div></div><button id="buy" class="primary" disabled>連接錢包後交易</button><p class="micro">首次交易需授權 mUSD。款項與憑證在同一筆交易中移轉，任一條件失敗則整筆回滾。</p><div id="trade-message" role="status"></div></aside></div>
<section class="deployment"><div><div class="eyebrow">TESTNET WORKSHOP</div><h2>建立自己的 ERC-3643 交易環境</h2><p>使用你的 Sepolia 錢包部署完整 T-REX 元件，簽署測試資格 Claim，建立兩批憑證與付款代幣。<br>共約 15 筆部署／設定交易與 2 次簽名，另需交易授權。僅消耗測試 ETH。</p></div><button id="deploy" disabled>先連接錢包</button><div class="progress"><div><span>01</span>身分與資格登錄</div><div><span>02</span>兩批 ERC-3643 憑證</div><div><span>03</span>mUSD 與 DvP 合約</div><div><span>04</span>驗證實際交易收據</div></div><pre id="deployment-log" role="status">尚未部署。本機驗證與公開 Sepolia 成果分開記錄。</pre></section>
<section class="evidence"><h2>驗證與資產界線</h2><div><p>使用 Tokeny T-REX 4.1.6 與 ONCHAINID 2.2.1。資格 Claim 由測試錢包自發，僅供演示，不代表完成法律 KYC。</p><p>DvP 驗證鏈上付款與憑證交割。真正的模型推理交付、供應商授權、儲備核验及爭議處理仍需鏈下機制。</p><p id="test-summary">正在讀取本地EVM測試證據…</p></div></section>
<footer><span>KorikoEX · RWA 設計工作坊 · 2026.10.01</span><nav><a href="https://eips.ethereum.org/EIPS/eip-3643" target="_blank" rel="noopener">ERC-3643</a><a href="https://openai.com/policies/service-credit-terms/" target="_blank" rel="noopener">額度轉讓條款</a><a id="github" href="https://github.com/k66inthesky/KorikoEX" target="_blank" rel="noopener">GitHub 原始碼 ↗</a></nav></footer></main>`;
const $=s=>document.querySelector(s);let provider,signer,state,selected='codex',busy=false;
const selectedWallet=discoverWallets(document.querySelector('#wallet-select'));
const storageKey=address=>`llm-exchange-v1:11155111:${address.toLowerCase()}`;
function save(v){state=v;localStorage.setItem(storageKey(v.owner),JSON.stringify(v));}
function log(msg){$('#deployment-log').textContent+='\n'+msg;}
function errorMessage(e){return e.shortMessage||e.reason||e.message||String(e);}
function updateQuote(){const n=Number($('#units').value);$('#tokens').textContent=Number.isInteger(n)&&n>0?(n*1000).toLocaleString()+' tokens':'—';$('#total').textContent=Number.isInteger(n)&&n>0?(n*(selected==='codex'?.5:.7)).toFixed(2)+' mUSD':'—';}
function renderReceipts(){const receipts=state?.trades||[];$('#receipts').replaceChildren();if(!receipts.length){$('#receipts').textContent='尚無公開測試網交割。完成交易後顯示實際 hash 與餘額變化。';return;}
 for(const r of receipts){const el=document.createElement('article');el.className='receipt';const title=document.createElement('b');title.textContent=`${r.batch.toUpperCase()} · ${r.units} 枚 · ${formatUnits(r.payment,6)} mUSD`;const a=document.createElement('a');a.href=`https://sepolia.etherscan.io/tx/${r.transactionHash}`;a.target='_blank';a.rel='noopener';a.textContent=r.transactionHash.slice(0,16)+'… ↗';const detail=document.createElement('p');detail.textContent=`區塊 ${r.blockNumber} · 收據狀態與雙方餘額已核對`;el.append(title,a,detail);$('#receipts').append(el);}}
async function refresh(){if(!state?.configured||!signer)return;const owner=await signer.getAddress();$('#identity').textContent=(await contract('IdentityRegistry',state.addresses.registry,provider).isVerified(owner))?'Claim 驗證通過':'未通過 Claim';$('#balance').textContent=formatUnits(await contract('MockUSD',state.addresses.cash,provider).balanceOf(owner),6)+' mUSD';for(const b of ['codex','claude'])$('#'+b+'-stock').textContent=String(await contract('Token',state.addresses[b],provider).balanceOf(state.addresses.dvp));$('#holdings').textContent=String(await contract('Token',state.addresses[selected],provider).balanceOf(owner))+' 枚';$('#buy').disabled=busy;$('#buy').textContent='確認 DvP 買入';$('#inventory-note').textContent='即時讀取 Sepolia 合約';renderReceipts();}
async function connect(){const wallet=selectedWallet();({provider,signer}=await connectSepolia(wallet));watchWallet(wallet);const address=await signer.getAddress();state=JSON.parse(localStorage.getItem(storageKey(address))||'null');$('#connect').textContent=address.slice(0,6)+'…'+address.slice(-4);$('#deploy').disabled=false;$('#deploy').textContent=state?.configured?'環境已建立':'部署 Sepolia PoC';$('#identity').textContent='已連接 · 待驗證';$('#deployment-log').textContent=state?.configured?'已載入本機儲存的測試網合約。':'錢包已連接。請確認有足夠測試 ETH，部署可中斷後繼續。';await refresh();}
$('#connect').onclick=()=>connect().catch(e=>{$('#trade-message').textContent=errorMessage(e)});
for(const offer of document.querySelectorAll('.offer')){const select=()=>{selected=offer.dataset.batch;document.querySelectorAll('.offer').forEach(x=>x.classList.toggle('active',x===offer));$('#selected').textContent=selected==='codex'?'Codex':'Claude';updateQuote();refresh().catch(e=>$('#trade-message').textContent=errorMessage(e));};offer.onclick=select;offer.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}};}
$('#units').oninput=updateQuote;$('#minus').onclick=()=>{$('#units').value=Math.max(1,Number($('#units').value)-1);updateQuote()};$('#plus').onclick=()=>{$('#units').value=Math.min(1000,Number($('#units').value)+1);updateQuote()};
$('#deploy').onclick=async()=>{if(busy||state?.configured)return;busy=true;$('#deploy').disabled=true;$('#buy').disabled=true;try{const balance=await provider.getBalance(await signer.getAddress());if(balance<10n**15n)throw Error('測試 ETH 不足。請先向 Sepolia faucet 領取測試 ETH。');state=await setup(signer,state||{},log,save);$('#deploy').textContent='環境已建立';log('所有元件與身分已建立。現在可交易 Codex／Claude 憑證。');}catch(e){log('停止：'+errorMessage(e));$('#deploy').textContent='繼續部署';}finally{busy=false;$('#deploy').disabled=false;await refresh().catch(e=>log(errorMessage(e)));}};
$('#buy').onclick=async()=>{if(busy)return;const n=Number($('#units').value);if(!Number.isSafeInteger(n)||n<1||n>1000){$('#trade-message').textContent='請輸入1至1000的整數。';return;}busy=true;$('#buy').disabled=true;$('#deploy').disabled=true;$('#trade-message').textContent='請在錢包確認授權與 DvP 交易，等待區塊確認。';try{const result=await trade(signer,state,selected,BigInt(n));state.trades??=[];state.trades.push(result);save(state);$('#trade-message').textContent='交割成功。已核對實際付款、憑證餘額與 Settled 事件。';}catch(e){$('#trade-message').textContent='交易未完成：'+errorMessage(e);}finally{busy=false;$('#deploy').disabled=false;await refresh().catch(e=>$('#trade-message').textContent=errorMessage(e));}};
$('#download').onclick=()=>{const blob=new Blob([JSON.stringify(state||{status:'not-deployed',chainId:11155111},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='sepolia-evidence.json';a.click();URL.revokeObjectURL(url);};

fetch('./local-evidence.json').then(r=>r.ok?r.json():Promise.reject()).then(e=>{$('#test-summary').textContent=`本地 EVM 已驗證：${e.checks.length} 項檢查通過，Codex／Claude 共 ${e.trades.length} 筆 DvP 成功。鏈 ID ${e.chainId}，屬本地測試，不是公開 Sepolia。`}).catch(()=>{$('#test-summary').textContent='本地測試證據尚未載入，請查看 GitHub 測試紀錄。'});
